// Headless smoke test of outputs/web/index.html (run: node tests/web_smoke.mjs). Exit code 1 on failure.
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url));
const url = pathToFileURL(path.join(here, '..', 'outputs', 'web', 'index.html')).href;
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM || undefined });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const errors = [];
page.on('pageerror', e => errors.push('pageerror: ' + e.message));
page.on('console', m => { if (m.type() === 'error' && !/ERR_|Failed to load resource/.test(m.text())) errors.push('console: ' + m.text()); });
await page.goto(url);
await page.waitForFunction('window.__APARRI_READY__ === true', null, { timeout: 15000 });
const r = {};
await page.screenshot({ path: path.join(here, '..', 'outputs', 'web', 'screenshot_overview.png') });
r.mapPanes = await page.locator('.leaflet-pane').count();
r.segPaths = await page.evaluate(() => document.querySelectorAll('#map canvas, #map svg').length);
r.options = await page.locator('#brgy option').count();
r.legend = (await page.locator('#legend').innerText()).includes('Low');
r.disclaimer = (await page.locator('.disclaimer').innerText()).includes('Academic use');
await page.selectOption('#brgy', 'Bulala Norte');
r.card = (await page.locator('#brgy-card').innerText()).includes('Table 4.2 row');
await page.fill('#year', '0').catch(()=>{});
await page.locator('#year').evaluate(e => { e.value = 1; e.dispatchEvent(new Event('input')); });
r.year = await page.locator('#yearout').innerText();
await page.check('#cb'); await page.check('#l-tr'); await page.check('#l-leg');
r.chart = (await page.locator('#chart svg').count()) === 1;
r.table = (await page.locator('#table42 table tr').count()) === 9;
await page.screenshot({ path: path.join(here, '..', 'outputs', 'web', 'screenshot_barangay_zoom.png') });
await browser.close();
const ok = errors.length === 0 && r.mapPanes > 0 && r.options === 9 && r.legend && r.disclaimer && r.card && r.year === '2000' && r.chart && r.table;
console.log(JSON.stringify({ ok, r, nErrors: errors.length, firstErrors: errors.slice(0, 5) }));
process.exit(ok ? 0 : 1);
