"""Renders docs/01_data_audit.md from the audit results (numbers are never typed by hand)."""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from .io import REPO_ROOT


def md(df: pd.DataFrame, floatfmt: str = "{:,.2f}", index: bool = False) -> str:
    d = df.reset_index() if index else df
    cols = [str(c) for c in d.columns]
    out = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, r in d.iterrows():
        cells = []
        for v in r.tolist():
            if isinstance(v, (float, np.floating)):
                cells.append("" if np.isnan(v) else floatfmt.format(v))
            else:
                cells.append(str(v))
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out)


def render(c: dict) -> Path:
    a, t, rr = c["a"], c["t"], c["rr"]
    tab = a["table"]
    pix, non = c["pix"], c["non"]
    yt, frag, cov, hc = c["yt"], c["frag"], c["cov"], c["hc"]
    px = c["px_ha"]
    jn = c["jn"]
    lb = c["lb"]

    n_pix = len(pix)
    ha_pix = pix.area_ha.sum()
    non_by = a["by_type"][~a["by_type"].pixel_type]
    conf = rr["confusion"]
    hig_under = rr["epr_under"]["Hig"]
    low_under = rr["epr_under"]["LOW"]
    med_under = rr["epr_under"]["Med"]
    # shares
    low_in_low = conf.loc["LOW", 1] / conf.loc["LOW"].sum()
    hig_row = conf.loc["Hig"]
    y2010 = yt[yt.year_raw == "2010"].iloc[0]
    lb_piv = lb.pivot_table(index="barangay", columns="year", values="min_distance_m").reindex(c["cfg"]["study_barangays"])
    lb_in = lb.pivot_table(index="barangay", columns="year", values="inside_km").reindex(c["cfg"]["study_barangays"])
    lb_tol = lb.pivot_table(index="barangay", columns="year", values="within_tol_km").reindex(c["cfg"]["study_barangays"])
    straight = jn[jn.method == "straight"].copy()
    straight["cls"] = straight.Risk_Level.str[:3].replace({"Hig": "High", "Med": "Medium", "LOW": "Low"})
    st = straight.pivot_table(index=straight.barangay.fillna("(outside every study barangay)"), columns="cls", values="area_ha", aggfunc="sum", fill_value=0.0)
    for k in ("Low", "Medium", "High"):
        if k not in st:
            st[k] = 0.0
    st = st[["Low", "Medium", "High"]]
    nobody = [b for b in c["cfg"]["study_barangays"] if b not in st.index]
    hig_c = hc.sort_values("median_dist_to_hig_m") if len(hc) else hc
    hz = hc.sort_values("length_of_year_inside_hig_zone_m") if len(hc) else hc

    ct = c["claims_tab"]
    n_missing_links = int((c["qf"]["layers"].found_on_disk == False).sum())  # noqa: E712
    n_local = int(c["qf"]["layers"].is_local_file.sum())
    lay = c["qf"]["layouts"]
    dbf_w = [f for f in c["dbf_risk"] if f["name"] == "Risk_Level"][0]
    dbf_year = [f for f in c["dbf_lines"] if f["name"] not in ("id",)][0]

    verdicts = {
        "attr": "CONFIRMED",
        "thr": "CONFIRMED",
        "pix": "CONFIRMED",
        "repro": "CONFIRMED (they cannot be reproduced)",
    }

    md_text = f"""# 01 — Data audit: legacy vector shorelines (B) and risk polygons (C)

*Generated by `make audit` (`src/aparri/audit.py`) — numbers are computed, not typed. Read-only: nothing in `data/raw/` was changed. All lengths/areas are in EPSG:32651 (metres). Verdicts: **CONFIRMED / REFUTED / INCONCLUSIVE** about the first-pass hypotheses in CLAUDE.md §4. Terms: **EPR** (End Point Rate) = shoreline movement between the first and last date divided by the years between them, m/yr, negative = landward = erosion. **NSM** (Net Shoreline Movement) = that movement in metres.*

## Executive summary (≤10 lines)

1. **Risk polygons (C): do not cite.** Only {len(a['distinct_epr'])} EPR values exist ({', '.join(f'{v:.4g}' for v in a['distinct_epr'])}); `Risk_Code` and `label` are the constant 1 in all {len(tab)} rows.
2. **Two different things are mixed in one layer.** {n_pix} polygons ({ha_pix:.1f} ha) are vectorised {px*1e4:.0f} m² raster cells (area = `count` × {px:.4f} ha; 100 % of vertices on the 30 m pixel lattice). The other {len(non)} polygons (all the 2.59 "Medium" and both "High" ones, {non.area_ha.sum():.1f} ha) have few vertices (median {int(non.n_vertices.median())}), **0 % on the lattice**, and cover 0.5–3.6 km each: they look **hand-drawn**.
3. **{t['n_violations']} polygons break the thesis rule itself** ("Medium" but EPR = 0.857 < 2) and **every EPR is positive**, i.e. *accretion* under the thesis sign convention.
4. **They cannot be reproduced from the Earth Engine rasters**: under the "High" polygons the raster has *no* High pixel (EPR between {hig_under['min']:.2f} and {hig_under['max']:.2f} m/yr); {rr['polygon_area_outside_raster_ha']:.1f} ha lie outside the raster extent.
5. **Shoreline lines (B): partly usable as context, not as measurements.** Years have 3–6 unjoined fragments, vertex spacing from {yt.mean_vertex_spacing_m.min():.0f} to {yt.mean_vertex_spacing_m.max():.0f} m, the 2010 coast is digitised **twice** in one stretch ({y2010.total_km:.1f} km listed, only ≈ {y2010.unique_km:.1f} km unique), and one feature has the year "Hig".
6. **Thesis text vs data:** the 2 hand-drawn High polygons do lie at Bulala Sur ({ct.loc['Bulala Sur','High']:.1f} ha) and Bulala Norte ({ct.loc['Bulala Norte','High']:.1f} ha), as the thesis says, but they also put {ct.loc['Linao','High']:.1f} ha of High in **Linao** (thesis: Low) and no Medium in Bulala Norte (thesis: Medium); the Earth Engine raster shows **no High on the Bulala coast at all** (§6).
7. **No demonstrated link** between Fig. 4.1/4.2, the lines, the polygons and the rasters: {n_missing_links} of {n_local} local layer links in the QGIS project are broken and no print layout locks its layer set (§7).
8. **Verdict — can we cite the legacy numbers? Risk polygons: NO. Shoreline lines: PARTLY** (as an unverified visual reference and as a candidate input to the rebuild, after cleaning; never as published rates).

---

## 1. Risk-layer attribute audit — {verdicts['attr']}

**Method.** Read `Aparri_MultiTemporal_Erosion_Risk_1990_2025.shp` (byte-identical to `Aparri Risk Ana.shp`, same sha256), tabulate labels, EPR values, `count`, geometry; compute areas in EPSG:32651.

| Fact | Result |
|---|---|
| Polygons / geometry types | {len(tab)} / {a['geom_types']} ({a['n_invalid']} invalid geometries, repaired in memory only) |
| Label spellings in the `.shp` | {', '.join(a['label_variants'])} — the `.dbf` field `Risk_Level` is **{dbf_w['type']}({dbf_w['width']})**: a {dbf_w['width']}-character text field, so "High"→"Hig" and "Medium"→"Med" were **truncated on export**. (`EPR Results.xlsx` has the un-truncated "High".) |
| Distinct EPR values | {len(a['distinct_epr'])}: {a['distinct_epr']} (the Earth Engine EPR raster has 128 distinct values) |
| `Risk_Code` / `label` | constant {a['distinct_code']} / {a['distinct_label']} — carry no information |
| NaN rows | {a['nan_rows']} |

Polygons and area per label:

{md(a['by_label'])}

Crosstab label × EPR (count of polygons):

{md(a['crosstab'], index=True)}

**What is `count`?** For {n_pix} polygons the ratio *area ÷ count* is **{pix.ha_per_count.mean():.4f} ha ± {pix.ha_per_count.std():.5f}**, equal to the area of one Landsat-grid pixel at this latitude ({px:.4f} ha; 28.5 m × 29.8 m). So for those polygons `count` **is a pixel count**. For the remaining {len(non)} polygons it is not (area ÷ count = {non.ha_per_count.min():.1f}–{non.ha_per_count.max():.1f} ha):

{md(non_by)}

## 2. Threshold consistency (Table 3.1) — {verdicts['thr']}

**Method.** Apply Low < 2, Medium 2–5, High > 5 m/yr to each polygon's own EPR (read as an erosion magnitude) and compare with its label.

* **{t['n_violations']} of {t['n']} polygons violate the rule**:

{md(t['violations_by_label'])}

* All EPR values are **positive** ({t['all_positive']}); the thesis states "negative = erosion", so read literally the layer describes *accretion*. Reading them as magnitudes (the only reading that gives a risk map) means the sign was dropped without a record.
* The two "High" polygons carry EPR 5.726 and the five "Medium (2.59)" polygons carry 2.586: they satisfy the rule, but these are exactly the hand-drawn polygons of §3.

## 3. Pixel-size hypothesis and reproduction from the rasters — {verdicts['pix']}

**Method.** (i) Is 0.857143 = 30/35? (ii) Do vertices lie on the 30 m lattice of the Earth Engine rasters (origin {rr['raster_bounds'][0]:.5f}, {rr['raster_bounds'][3]:.5f}; cell 0.00026949°)? (iii) Rasterise the polygons onto the Earth Engine risk raster and cross-tabulate.

* 30/35 = {30/35:.6f} → **0.857143 is exactly one 30 m pixel of change over 35 years.** It is a class constant for the smallest possible change, not a measured mean. 2.5864 × 35 = {2.5864*35:.2f} m and 5.72642 × 35 = {5.72642*35:.1f} m are **not** multiples of 30 m: they cannot come from the pixel-distance method — **REFUTED** for those two values.
* Vertex-on-lattice test (tolerance 2 % of a cell; chance level ≈ 4 %):

| Layer / subset | vertices | on lattice (x) | on lattice (y) | both |
|---|---|---|---|---|
| Risk polygons, all | {c['g_all']['n_vertices']} | {c['g_all']['on_grid_x']:.1%} | {c['g_all']['on_grid_y']:.1%} | {c['g_all']['on_grid_both']:.1%} |
| …pixel-type polygons ({n_pix}) | {c['g_pix']['n_vertices']} | {c['g_pix']['on_grid_x']:.1%} | {c['g_pix']['on_grid_y']:.1%} | {c['g_pix']['on_grid_both']:.1%} |
| …other polygons ({len(non)}) | {c['g_non']['n_vertices']} | {c['g_non']['on_grid_x']:.1%} | {c['g_non']['on_grid_y']:.1%} | {c['g_non']['on_grid_both']:.1%} |
| Shoreline lines (B) | {c['g_lines']['n_vertices']} | {c['g_lines']['on_grid_x']:.1%} | {c['g_lines']['on_grid_y']:.1%} | {c['g_lines']['on_grid_both']:.1%} |

  → the {n_pix} pixel-type polygons are **vectorised raster cells on the same lattice as our rasters**; the {len(non)} others and **all shoreline lines were not made from a raster** (CONFIRMED).
* Reproduction test — pixels of the Earth Engine **risk raster** (rows = polygon label, columns = raster class 1 Low / 2 Medium / 3 High):

{md(conf, index=True)}

  Raster totals: Low {rr['raster_class_pixels'][1]:,} · Medium {rr['raster_class_pixels'][2]:,} · High {rr['raster_class_pixels'][3]:,}. Of the raster's {rr['raster_class_pixels'][3]} High pixels, only {rr['raster_class_inside_any_polygon'][3]} lie in any polygon and those fall mostly in *Low* polygons.
  EPR values of the raster under the polygons: **High polygons** n={hig_under['n']}, min {hig_under['min']:.2f}, median {hig_under['median']:.2f}, max {hig_under['max']:.2f} m/yr; **Medium polygons** min {med_under['min']:.2f}, median {med_under['median']:.2f}; **Low polygons** min {low_under['min']:.1f}, median {low_under['median']:.2f}.
  Only {low_in_low:.0%} of the pixels under *Low* polygons are Low in the raster, and **no** pixel under a *High* polygon is High.
* Extent: {rr['polygon_area_outside_raster_ha']:.1f} ha of polygon area lies outside the raster footprint (x 121.580–121.720, y 18.330–18.390), so a full reproduction is impossible even in principle.

**Verdict: the polygons cannot be reproduced from the Earth Engine rasters.** Their origin is some other run (or manual work) that was never supplied.

## 4. Shoreline-layer audit

**Method.** Reproject to EPSG:32651; per feature compute length, vertices, self-crossing (`is_simple`), duplicate vertices, endpoint gaps to the nearest other fragment of the same year and the share that runs within 15 m of another fragment of the same year.

* The layer's year column is literally named **"{dbf_year['name']}"** (type {dbf_year['type']}({dbf_year['width']})) and `id` is empty in all rows → the table was imported with its first data row used as the header.

{md(yt)}

* **2010 is {y2010.total_km:.1f} km because part of the coast was digitised twice.** Features 3, 10 and 11 overlap each other for up to {y2010.max_overlap_frac:.0%} of their length; counting each stretch once (duplicates digitised up to 60 m apart) gives ≈ **{y2010.unique_km:.1f} km** (duplicated ≈ {y2010.duplicated_km:.1f} km). **CONFIRMED** as the reason for the unusual total.
* Other years: 1990 {yt[yt.year_raw=='1990'].total_km.iloc[0]:.1f} km, 2020 {yt[yt.year_raw=='2020'].total_km.iloc[0]:.1f} km differ from 2000/2025 (≈ 41 km) because fragments are missing, not because the coast changed: see the gaps below.
* Vertex density differs 5-fold between years (mean spacing {yt.mean_vertex_spacing_m.min():.0f}–{yt.mean_vertex_spacing_m.max():.0f} m; the 1990 SE open coast is 33 vertices over 18.5 km = 577 m!). Lines digitised at such different detail are **not comparable** at the metre level that a 0.86 m/yr rate needs.
* Self-crossing features (loops): {', '.join(str(int(x)) for x in frag[~frag.is_simple].fid)} (fid) — river-mouth loops.

Fragments (fid = row number in the shapefile):

{md(frag[['fid','year_raw','length_km','n_vertices','mean_vertex_spacing_m','is_simple','dup_vertices','gap_start_m','gap_end_m','overlap_with_same_year_frac']])}

* **Gaps.** Between fragments of the same year the endpoint gaps are up to {max(frag.gap_start_m.max(), frag.gap_end_m.max())/1000:.1f} km (e.g. 1990 fid 2 starts {frag[frag.fid==2].gap_start_m.iloc[0]/1000:.1f} km from the nearest other 1990 fragment): the gaps coincide with the Cagayan River mouth, which was left open in every year. A "continuous shoreline" does not exist in any year.
* **Coverage / common extent.** Projecting every vertex on the NW→SE axis of the coast, every year covers {cov[cov.year_raw=='1990'].t_min_km.iloc[0]:.1f}–{cov[cov.year_raw=='1990'].t_max_km.iloc[0]:.1f} km; the common extent of the five years is {cov.attrs['common_extent_km'][0]:.2f}–{cov.attrs['common_extent_km'][1]:.2f} km, i.e. essentially the whole 21.8 km — **extent is not the problem**; fragment gaps and the duplicated 2010 stretch are.

### The feature labelled "Hig"

Feature {c['hig_fid']} (3.1 km, x≈351,6–351,7 E, y≈2,032,3 N, Bulala Norte–Linao coast) has the text "Hig" in the year column — the same truncation word as the risk layer, so it was probably pasted from it. **Its true year is not assigned here.** Evidence for a human to weigh:

{md(hc)}

Reading: a year that has *no* line near this stretch is a candidate (least length inside the 100 m zone: **{hz.iloc[0].year_raw}**, then {hz.iloc[1].year_raw}); the year whose lines run closest to it (median distance) is **{hig_c.iloc[0].year_raw}**. The two criteria disagree, so the answer is **INCONCLUSIVE** — the students must tell us or the feature stays excluded (Phase 3A rule).

## 5. Spatial-join audit

**Method.** Compare (a) straight intersection with the eight study-barangay polygons and (b) nearest-within-{c['tol']:.0f} m (each 10 m sample point of a polygon is given to the nearest barangay within tolerance).

*Length (km) of each year's lines inside each barangay polygon (straight intersection):*

{md(lb_in, index=True)}

*Same, within {c['tol']:.0f} m:*

{md(lb_tol, index=True)}

*Minimum distance (m) from the year's lines to the barangay polygon:*

{md(lb_piv, floatfmt='{:,.0f}', index=True)}

* **Straight intersection loses the coast**: Bulala Norte, Bulala Sur, San Antonio get ≈ 0 km of shoreline, because the barangay polygon edge *is* the old coastline. The distances above even reveal a signal: the 1990 line lies {lb_piv.loc['Bulala Norte','1990']:.0f} m (Bulala Norte) / {lb_piv.loc['Bulala Sur','1990']:.0f} m (Bulala Sur) **seaward** of the polygon edge while the 2025 line lies within {lb_piv.loc['Bulala Norte','2025']:.0f} m — consistent with landward retreat along the Bulala coast (to be measured properly in Phase 4).
* Risk polygons by straight intersection (ha):

{md(st, index=True)}

  Study barangays with **no** polygon area at all under straight intersection: **{', '.join(nobody) if nobody else 'none'}**. ({len(non)} hand-drawn polygons mostly lie over water just off the land polygons.)
* Under nearest-within-{c['tol']:.0f} m the picture is different (§6). **A tolerance join is required** (config `barangay_join_tolerance_m`).

## 6. Thesis text vs legacy data — CONFIRMED contradictions

Chapter IV says: *High* in Bulala Sur and Bulala Norte; *Medium* in Bulala Norte, Punta, San Antonio, Maura, Dodan, Paddaya; *Low* in Linao. Area (ha) by class, nearest-within-tolerance attribution:

{md(ct, index=True)}

Contradictions found:

""" + "\n".join(f"* {n}" for n in c["notes"]) + f"""

(The Earth Engine barangay table is audited in `docs/01b_gee_audit.md`; the Earth Engine rasters give only ≈ 1.4 ha of High inside the eight official polygons — Linao 1.27 ha, Maura 0.17 ha — and **none in Bulala Sur or Bulala Norte**.)

## 7. QGIS-project forensics

* QGIS {c['qf']['qgis_version']}, saved **{c['qf']['saved']}** by "{c['qf']['saved_by']}", project CRS **{c['qf']['project_crs']}** (not metric-safe). The manuscript is dated April 2026, so the project is *newer* than the figures printed in it.
* Visibility presets: {c['qf']['visibility_presets'] or 'none'}; processing history stored: {c['qf']['has_processing_history']} → **no record of how any layer was produced.**

{md(c['qf']['layers'][['layer','type','crs','is_local_file','found_on_disk','renderer_field']])}

* {n_missing_links} of {n_local} local sources are **broken** (point to `../../../Downloads/...`): the rasters and the risk shapefile (named `Risk`), and `Shoreline Changes 1990-2025.shp` — a file that was never supplied (the supplied one is `Shoreline Changes.shp`). Two different Earth Engine export folders appear in the paths (`Final_Aparri_Erosion_Assessment`, `Aparri_Erosion_Assessment-20260917T050811Z-1-001`): **at least two export runs exist**.

{md(lay)}

* Figure ↔ layer: Layout 4's title ("Coastal Erosion Risk Map of Selected Coastal Barangays in Aparri…") matches thesis **Fig. 4.2**; the thesis Fig. 4.1 title ("Multi-Temporal Shoreline Change Map of Selected Coastal Barangays…") matches **no saved layout exactly** (Layouts 1 and 3 have a shorter title). `layer_set_locked = False` for every map item: a layout shows whatever is ticked in the project *at export time*, so the project cannot prove which layer made which figure. The exported draft maps (`Erosion Risk Map.jpeg`, `Multi Temporal Risk.jpeg`) show only green cells.
* **Is there any demonstrated link between the lines (B), the polygons (C) and the rasters (A)?** Only a weak one: B and C have almost the same bounding box (x 121.563–121.755, y 18.319–18.392), larger than the rasters', suggesting the same working AOI; and {n_pix} polygons sit on the rasters' pixel lattice. Nothing shows B was derived from A or C from A. **INCONCLUSIVE → treat as unlinked.**

## 8. Diagnostic maps

`outputs/maps/audit_risk_by_label.png` (polygons by label; hand-drawn ones outlined), `audit_shoreline_fragments_by_year.png` (fragments and endpoints per year), `audit_river_mouth_zoom.png` (same, river-mouth area), `audit_barangay_edges.png` (coast vs barangay edges). Tables: `outputs/tables/audit_*.csv`.

## What this means for the rebuild

* Use none of the legacy **numbers**. The legacy **lines** can seed the rebuilt analysis only after cleaning (Phase 3A) and only if the students can tell us how they were made; they are compared with an independent raster-derived set in Phase 3B.
* Questions the data cannot answer (CLAUDE.md §6 "Open questions"): who drew the 7 large polygons and the 20 lines; the true year of the "Hig" feature; why 2010 has a duplicated stretch; which export run feeds Fig. 4.2.
"""
    out = REPO_ROOT / "docs" / "01_data_audit.md"
    out.write_text(md_text, encoding="utf-8")
    return out
