"""Renders docs/01b_gee_audit.md from the Phase 2B results (numbers computed, not typed)."""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from .audit_report import md
from .io import REPO_ROOT


def render(c: dict) -> Path:
    r, inv, leg, qn = c["r"], c["inv"], c["leg"], c["qn"]
    ext, noise, plaus, legacy, repro, comp, off = c["ext"], c["noise"], c["plaus"], c["legacy"], c["repro"], c["comp"], c["official"]
    cfg = c["cfg"]
    order = cfg["table_4_2_order"]
    P = plaus.set_index("set")
    acc, ero, hi, me = P.loc["Accretion pixels (code 2)"], P.loc["Erosion pixels (code 1)"], P.loc["Risk High (3)"], P.loc["Risk Medium (2)"]
    n25 = noise[noise.year == 2025].iloc[0]; n90 = noise[noise.year == 1990].iloc[0]
    ratio_edge = n25.edge_pixels / n90.edge_pixels
    acc_ha_nosea = (acc.pixels - acc.sea_px) * r.px_ha
    ratio_pix = acc.pixels / ero.pixels

    # side-by-side table in thesis Table 4.2 order
    lg = legacy.set_index("Barangay"); rp = repro.set_index("Barangay"); of = off.set_index("Barangay")
    side = pd.DataFrame({
        "legacy Low ha": lg.Low_ha, "legacy Med ha": lg.Medium_ha, "legacy High ha": lg.High_ha, "legacy mean EPR": lg.Mean_EPR,
        "legacy area basis ha": [np.pi * 100 if False else (rp.loc[b, 'area_ha'] if b in rp.index else np.nan) for b in lg.index],
    }).reindex(order)
    side2 = pd.DataFrame({
        "polygon ha": of.polygon_ha, "raster covers %": of.raster_cover_of_polygon_pct,
        "Med ha (inside)": of.Medium_ha_exact, "High ha (inside)": of.High_ha_exact,
        "Med ha (+500 m)": of.Medium_ha, "High ha (+500 m)": of.High_ha,
        "mean EPR eroding px": of.Mean_EPR_eroding_px,
    }).reindex(order)
    cmp_rows = []
    for b in order:
        if b in comp.Barangay.values:
            row = comp[comp.Barangay == b].iloc[0]
            def pct(a, bb):
                return np.nan if (pd.isna(a) or pd.isna(bb) or a == 0) else (bb - a) / a * 100
            cmp_rows.append({"Barangay": b, "Low ha csv": row.Low_ha_csv, "Low ha repro": row.Low_ha_repro, "diff %": pct(row.Low_ha_csv, row.Low_ha_repro),
                             "High ha csv": row.High_ha_csv, "High ha repro": row.High_ha_repro,
                             "Min EPR csv": row.Min_EPR_csv, "Min EPR repro": row.Min_EPR_repro,
                             "Max EPR csv": row.Max_EPR_csv, "Max EPR repro": row.Max_EPR_repro,
                             "Mean EPR csv": row.Mean_EPR_csv, "Mean EPR repro": row.Mean_EPR_repro})
    cmp_df = pd.DataFrame(cmp_rows)
    circle_ha = np.pi * (cfg["legacy_barangay_points_buffer_m"] / 100) ** 2
    nan_rows = [b for b in legacy.Barangay if pd.isna(legacy.set_index("Barangay").loc[b, "Mean_EPR"])]
    low_near_circle = int(((legacy.Low_ha / circle_ha) > 0.95).sum())

    text = f"""# 01b — Audit of the Google Earth Engine raster pipeline (product A)

*Generated by `make audit-gee` (`src/aparri/audit_gee.py`). Read-only; all numbers are computed from the files in `data/raw/gee_outputs/`. Vocabulary: **NSM** = metres moved between 1990 and 2025; **EPR** = NSM ÷ 35 yr (m/yr, negative = erosion); a **pixel** is a Landsat-grid cell of {r.px_m_ew:.1f} × {r.px_m_ns:.1f} m = {r.px_ha:.4f} ha.*

## Executive summary (≤12 lines)

1. The script (`Code.docx`) is a plain, readable Landsat/NDWI workflow, and its **risk rule matches the thesis thresholds** (verified pixel by pixel: {leg['risk_matches_rule_pixels']:,} of {leg['risk_pixels']:,} risk-raster pixels equal the rule applied to the EPR raster).
2. But it measures **land↔water change between 1990 and 2025 only**; 2000/2010/2020 never enter any rate, and NSM is a **pixel-distance approximation** (the script says so itself).
3. **"Accretion" is an artefact:** {int(acc.pixels):,} accretion pixels ({acc.ha:,.0f} ha) vs {int(ero.pixels):,} erosion pixels ({ero.ha:,.0f} ha) = **{ratio_pix:.0f}×**; **{acc.sea_pct:.0f} % of the accretion pixels lie in the open sea** and {acc.line_no_mapped_shoreline_within_band/acc.pixels:.0%} are > 150 m from any mapped shoreline.
4. **The years are not comparable:** edge pixels per year {', '.join(f'{int(v):,}' for v in noise.edge_pixels)}; in 2025 {n25.share_sea:.0%} of them are in open water (0 % in 1990–2010). 2025 has **{ratio_edge:.1f}×** the edge pixels of 1990.
5. **No High pixel is on the open coast:** of {int(hi.pixels)} High pixels, {int(hi.line_near_open_coast_line)} are near an open-coast line and {int(hi.line_near_river_estuary_line)} are near river/estuary banks (Cagayan River mouth). Medium: {int(me.line_near_open_coast_line)} open-coast, {int(me.line_near_river_estuary_line)} river/estuary.
6. **Barangay table = 1 km circles around single points** (confirmed: reproduced within ≈ 1–5 %). `Low_Risk_ha` ≈ circle area ({circle_ha:.0f} ha) for {low_near_circle} of 8 rows; **{', '.join(nan_rows)}** have no EPR (point outside the box); Dodan is clipped to {lg.Low_ha['Dodan']:.0f} ha.
7. Recomputed with the **official polygons**, the raster has **{of.High_ha_exact.sum():.2f} ha of High inside the eight polygons** (+500 m tolerance: {of.High_ha.sum():.2f} ha, in {', '.join(of.index[of.High_ha > 0])}); Bulala Sur is outside the raster and Paddaya is {of.loc['Paddaya','raster_cover_of_polygon_pct']:.1f} % covered.
8. **Verdict:** the raster pipeline is *usable as a screening hint*, **not** as the source of Table 4.2, Fig. 4.2 or any rate (verdict table §6).
9. **Decisions needed** (Decision Gates #1–#4): who wrote/ran the script and whether the thesis will describe it as the method; whether anything from the 1 km statistics reached the thesis; which shoreline set is primary (Phase 3B comparison); and whether Landsat may be re-fetched (Phase 3C). Phase 3C **cannot run in this sandbox** (Landsat catalogues unreachable, no Earth Engine login) — see `docs/decisions.md` D-04.

---

## 1. Method card (what the script does, in plain English)

| Step | What the script does | Script section | Problem / caution |
|---|---|---|---|
| Area | One rectangle: lon {cfg['legacy_gee_aoi'][0]}–{cfg['legacy_gee_aoi'][2]}, lat {cfg['legacy_gee_aoi'][1]}–{cfg['legacy_gee_aoi'][3]} | §1 | Misses Bulala Sur (lon 121.566) and Paddaya (lat 18.310); clips Dodan (lat 18.324) |
| Sensors | ≤ 2012: Landsat 4 + 5 + 7; 2013–2020: Landsat 8; 2021+: Landsat 8 + 9. Collection 2 Level-2 surface reflectance | §3, §6 | 1990 relies on Landsat 4/5 only; Landsat 7 (used for 2000 and 2010) has the scan-line-corrector gaps after May 2003 |
| Composite | For each calendar year: **median** of all scenes (Jan–Dec, every season and tide) | §6 | Mixes wet/dry season, tide, river stage; image counts are printed but were never saved; acquisition dates are not recorded |
| Cloud mask | QA_PIXEL bits: fill (bit 1 dilated cloud), cloud (3), shadow (4); cirrus (2) for Landsat 8/9 | §4–5 | Only these flags; no water-confidence or glint handling |
| Water index | NDWI = (Green − NIR)/(Green + NIR) **> 0**, fixed threshold | §7–8 | One global threshold for all years and sensors; no calibration; masked pixels are later set to 0 (= land) |
| "Shoreline" | Pixels where a 3×3 maximum differs from the 3×3 minimum of the water mask | §11 | An **edge band** about 2 pixels thick (≈ 60 m), not a line; any speckle produces "shoreline" |
| Change | Erosion = land in 1990 and water in 2025; accretion = water in 1990 and land in 2025 | §13–15 | Only two years; a cloud hole or a mask error in either year becomes "change" |
| NSM | Distance to the nearest 1990 edge pixel (erosion, negative) or 2025 edge pixel (accretion, positive), × 30 | §17–18 | "A raster-distance approximation… a transect-based NSM is preferable" (script's own note); × 30 ignores the real {r.px_m_ew:.1f}/{r.px_m_ns:.1f} m pixel; distance search capped at 256 px |
| EPR | NSM ÷ 35 | §19 | Every non-zero value is a pixel multiple (smallest 0.857 = 30/35) |
| Risk | 1 Low (default, includes accretion, stable land **and open sea**); 2 Medium if EPR<0 and 2 ≤ \\|EPR\\| ≤ 5; 3 High if EPR<0 and \\|EPR\\| > 5 | §22–24 | Matches Table 3.1 thresholds (inclusive 2 and 5) |
| Barangays | 8 **points** → 1 km radius circles; mean/min/max, hectares per class | §28–31 | Script: "temporary… replace with official boundaries" |
| Exports | CSV, SHP, 9 GeoTIFFs, EPSG:4326, 30 m | §32–38 | No metadata; vector shorelines and risk polygons are **not** exported by this script |

**Not recorded anywhere:** image count and acquisition dates per year, seasons, tide state, cloud fraction, NDWI values, who ran it and when.

## 2. Raster audit

{md(inv[['file','crs','width','height','dtype','distinct_values','min','max']])}

* CRS EPSG:4326 for all; 521 × 223 px; **{r.px_m_ew:.2f} m (E–W) × {r.px_m_ns:.2f} m (N–S)** at this latitude — pixels are not square, so `distance × 30` is only an approximation. Extent x {r.bounds.left:.4f}–{r.bounds.right:.4f}, y {r.bounds.bottom:.4f}–{r.bounds.top:.4f} (the requested box, snapped to the pixel grid). No NoData value is set.
* **Class legend** (not documented in the files; inferred from the script §14–15 and §37, then tested): `Erosion_Accretion` 0 = none, **1 = erosion**, **2 = accretion**; `Erosion_Risk` 1 Low, 2 Medium, 3 High. Tests: code 0 ⇒ NSM = 0 for all {leg['n_code'][0]:,} pixels: {not bool(leg['nonzero_nsm_where_code0'])}; erosion pixels have NSM ≤ 0: {leg['code1_all_nsm_nonpositive']} ({leg['code1_nsm_exactly_zero']} are exactly 0 – they sit on the 1990 edge itself); accretion pixels NSM ≥ 0: {leg['code2_all_nsm_nonnegative']}; EPR = NSM/35 everywhere: {leg['epr_equals_nsm_over_35']}; risk raster = rule(EPR): {leg['risk_matches_rule_pixels']==leg['risk_pixels']}. **Legend CONFIRMED (high certainty).**
* Pixel counts / hectares: none {leg['n_code'][0]:,} ({leg['ha_code'][0]:,.0f} ha) · erosion {leg['n_code'][1]:,} ({leg['ha_code'][1]:,.0f} ha) · accretion {leg['n_code'][2]:,} ({leg['ha_code'][2]:,.0f} ha); risk Low {leg['risk_class_counts'][1]:,} ({leg['risk_class_ha'][1]:,.0f} ha) · Medium {leg['risk_class_counts'][2]} ({leg['risk_class_ha'][2]:.1f} ha) · High {leg['risk_class_counts'][3]} ({leg['risk_class_ha'][3]:.1f} ha).
* **Quantisation:** {qn['distinct_epr']} distinct EPR values; {qn['share_nsm_over30_squared_is_integer']:.0%} of non-zero NSM satisfy (NSM/30)² = integer, i.e. NSM = 30·√(a²+b²) for whole-pixel offsets (a, b). Smallest |NSM| = {qn['smallest_abs_nsm']:.0f} m, smallest |EPR| = {qn['smallest_abs_epr']:.4f} = 30/35 = {qn['thirty_over_35']:.4f}. **Resolution of the method is one pixel (≈ 30 m ≈ 0.86 m/yr); the Low/Medium boundary (2 m/yr) is only 2.3 pixels.**
* **Extreme values** (EPR < −14 m/yr): {len(ext)} pixels, all along the bottom edge of the box at lon ≈ {ext.lon.min():.3f}–{ext.lon.max():.3f}, lat ≈ {ext.lat.min():.3f}–{ext.lat.max():.3f} (zone: {', '.join(sorted(set(ext.zone)))}). They are artefacts of the box edge / the 256-pixel distance cap (NSM down to {r.nsm.min():,.0f} m). Full list: `outputs/tables/gee_extreme_epr_pixels.csv`.

### Why is 2025 about {ratio_edge:.0f}× noisier than 1990?

{md(noise)}

* Edge pixels grow from {int(n90.edge_pixels):,} (1990) to **{int(n25.edge_pixels):,}** (2025); the number of separate pieces from {int(n90.components)} to {int(n25.components)}, and {n25.share_sea:.0%} of the 2025 edge pixels (and {noise[noise.year==2020].iloc[0].share_sea:.0%} of 2020's) lie in the **open sea** where there is no shoreline, against 0 % in 1990, 2000 and 2010. See `outputs/maps/gee_edge_noise_by_year.png`.
* **What is certain:** the 2020 and 2025 water masks break up over open water. **What is not certain (HYPOTHESIS):** the cause. Candidates: a fixed NDWI > 0 threshold behaving differently on Landsat 8/9 than on 4/5/7 over turbid sea water (river sediment plume, glint), different numbers of scenes per year, or cloud holes set to land. The NDWI values were never exported, so this cannot be tested from the files.

## 3. Plausibility tests

Zones: *open coast* = within {cfg['scope']['hull_tolerance_m']} m of the sea-facing outline of all legacy shorelines (`scope.py`); *sea* = beyond it; the rest lies inside the municipal polygons (which include the Cagayan River) or outside them in the river mouth. "Nearest legacy line" uses only the supplied vector lines (product B), 150 m band.

{md(plaus.T.reset_index().rename(columns={'index':'measure'}), floatfmt='{:,.1f}')}

* (a) **Where are the {int(hi.pixels)} High and {int(me.pixels)} Medium pixels?** High: {int(hi.line_near_open_coast_line)} near the open coast, **{int(hi.line_near_river_estuary_line)} near river/estuary banks**, {int(hi.line_no_mapped_shoreline_within_band)} near no mapped shoreline. Medium: {int(me.line_near_open_coast_line)} / {int(me.line_near_river_estuary_line)} / {int(me.line_no_mapped_shoreline_within_band)}. See `outputs/maps/gee_high_medium_pixels.png`.
* (b) **Are they on the open coast, river mouth, ponds?** Mostly the Cagayan River mouth (Linao spit, sandbars, banks); fishponds/inland water cannot be separated without the NDWI image.
* (c) **Does NDWI>0 create inland "shorelines"?** Yes, by construction: any water body (river, pond, paddy) has an edge. {noise[noise.year==1990].iloc[0].share_land:.0%} of 1990 edge pixels are inside municipal polygons away from the open coast. The script never separates "coast" from "inland water".
* (d) **Accretion {ratio_pix:.0f}× erosion — physical or artefact?** Artefact: **{acc.sea_pct:.1f} % of accretion pixels are in the open sea** (zone *sea*), {acc.line_no_mapped_shoreline_within_band/acc.pixels:.1%} are > 150 m from any mapped shoreline. Water in 1990, "land" in 2025, over the sea: this is the 2025 mask failing. If the sea block is discarded, accretion falls from {acc.ha:,.0f} ha to ≈ {acc_ha_nosea:,.0f} ha (vs erosion {ero.ha:,.0f} ha). `outputs/maps/gee_zones_and_change.png`.

## 4. Barangay statistics audit

**4a. Reproduction of the CSV** from the rasters with 1 km circles around the script's points (pixels weighted by the fraction inside the circle, like Earth Engine's `reduceRegion`):

{md(cmp_df)}

* Min/Max EPR reproduce to ≥ 6 decimals; areas to within ≈ 1.5–5 % (Earth Engine's circle is approximate); means to a few percent. **CONFIRMED: the CSV is exactly "statistics inside a 1 km circle around one point".**
* `Low_Risk_ha` is ≈ the circle area ({circle_ha:.0f} ha) because "Low" contains every unchanged pixel (land and sea): not a coastal quantity.
* **{', '.join(nan_rows)}**: NaN / zero – their points lie outside the box; Dodan's circle is clipped ({lg.Low_ha['Dodan']:.0f} ha).

**4b. Same statistics with the OFFICIAL study-barangay polygons** (pixel centre inside the polygon, or nearest within {cfg['barangay_join_tolerance_m']} m):

{md(side2, index=True)}

* *Inside* = pixel centre inside the polygon; *+500 m* adds the sea-side strip (the coast is the polygon edge). Bulala Sur is entirely outside the raster; Paddaya {of.loc['Paddaya','raster_cover_of_polygon_pct']:.1f} % covered; Dodan {of.loc['Dodan','raster_cover_of_polygon_pct']:.0f} %; Bulala Norte {of.loc['Bulala Norte','raster_cover_of_polygon_pct']:.0f} %.
* Side by side with the legacy CSV (Low/Med/High ha):

{md(pd.DataFrame({'legacy Low': lg.Low_ha, 'legacy Med': lg.Medium_ha, 'legacy High': lg.High_ha, 'official+500m Low': of.Low_ha, 'official+500m Med': of.Medium_ha, 'official+500m High': of.High_ha}).reindex(order), index=True)}

  (`outputs/maps/gee_stats_comparison.png`.) Neither version is a valid Table 4.2: both mix sea pixels into "Low".

## 5. Sensitivity of the raster method

Only the binary edge masks and the derived rasters were exported — **no NDWI image**. A threshold sweep (−0.1/0/+0.1) is therefore impossible from the files. What Phase 3C would need: (i) the per-year NDWI (or MNDWI/AWEI) composites saved as rasters, (ii) the list of scenes used (id, date, sensor, cloud %), (iii) a per-composite threshold (Otsu) instead of 0, (iv) a seasonal window and a tide estimate, (v) a sub-pixel contour. `src/aparri/landsat.py` and `scripts/gee_v2.js` implement this; it **was not run** here (no network route to Landsat, no Earth Engine login).

## 6. Verdict: which thesis claims depend on this pipeline?

| Claim in the thesis | Depends on | Verdict | Reason |
|---|---|---|---|
| Shorelines for 1990–2025 were digitised from satellite images (Ch. III–IV) | A or B | **NOT USABLE as worded** | Product A is an automatic edge-pixel mask, not digitising; method text must be rewritten |
| Fig. 4.1 five-year shoreline overlay | B | n/a to A | Compare in Phase 3B; A's masks for 2020/2025 are noisy over water |
| Shoreline masks 1990, 2000, 2010 (A) | A | **USABLE WITH CAVEATS** | Consistent noise level (≈ 2.4–2.7 k px); 30 m, edge band ±1 px |
| Shoreline masks 2020, 2025 (A) | A | **NOT USABLE directly** | {n25.share_sea:.0%} of 2025 edge pixels in open water; needs cleaning (Phase 3B) |
| EPR 1990–2025 per pixel (A) | A | **NOT USABLE** | Pixel-distance approximation; driven by mask artefacts; one-pixel resolution ≈ 0.86 m/yr |
| Erosion / accretion areas | A | **NOT USABLE** | Accretion {acc.sea_pct:.0f} % over open sea |
| Risk raster thresholds (Low <2, Medium 2–5, High >5) | A | **USABLE** | Rule matches Table 3.1 exactly (inclusive 2 and 5) |
| Risk raster as a map (Fig. 4.2) | A | **NOT USABLE** | "Low" includes land and sea; High pixels sit in the river mouth, not on the open coast |
| Locations of Medium/High pixels | A | **USABLE WITH CAVEATS** | Screening hint of hot spots (river-mouth sandbars, Linao spit); not a rate |
| Table 4.2 (mean/min/max EPR, Low/Medium/High ha per barangay) from the CSV | A (CSV) | **NOT USABLE** | 1 km circles around points; NaN/zero rows; Low ≈ circle area |
| "Mean EPR" of a barangay | A | **NOT USABLE** | Average of mostly zero pixels incl. sea |
| Statement that 2000/2010/2020 shorelines informed the analysis | A | **NOT SUPPORTED** | Not used in any rate (script §13–19) |

## 7. What must be decided (Decision Gates #1–#4)

1. **Gate 1 / 2:** Who wrote and ran `Code.docx`, and did any value from the 1 km CSV go into the thesis or defense slides? (The empty Table 4.2 suggests not.)
2. **Gate 3:** Which shoreline set is primary — decided after the Phase 3B comparison.
3. **Gate 4:** May Landsat be re-fetched (own Earth Engine account / open STAC)? **Not possible in the current sandbox**; the students can run `scripts/gee_v2.js` themselves.

Files: tables `outputs/tables/gee_*.csv`; maps `outputs/maps/gee_*.png`.
"""
    out = REPO_ROOT / "docs" / "01b_gee_audit.md"
    out.write_text(text, encoding="utf-8")
    return out
