"""Figures and the markdown report for Phase 6 (numbers computed, not typed)."""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from .audit_report import md
from .io import REPO_ROOT


def _plt():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    return plt


def figures(res: dict, cfg: dict, out: Path) -> None:
    plt = _plt()
    runs = res["runs"].copy()
    fig, ax = plt.subplots(figsize=(11, 5))
    x = np.arange(len(runs)); b = np.zeros(len(runs))
    for c, col in (("Low", "#2e8b57"), ("Medium", "#ffa500"), ("High", "#e31a1c")):
        ax.bar(x, runs[f"pct_{c}"], bottom=b, color=col, label=c); b += runs[f"pct_{c}"].values
    ax.set_xticks(x); ax.set_xticklabels(runs.scenario, rotation=35, ha="right", fontsize=8); ax.set_ylabel("% of valid transects")
    ax.set_title("Sensitivity: share of the open coast in each class under 11 alternative (equally reasonable) choices", fontsize=10)
    ax.legend(loc="lower right", fontsize=8); fig.tight_layout(); fig.savefig(out / "Fig_6_sensitivity_class_shares.png", dpi=200); plt.close(fig)

    ma = res["ma"]; v = ma["v"]
    fig, ax = plt.subplots(1, 2, figsize=(12, 5))
    ax[0].scatter(v.EPR_m_yr, v.lrr, s=8, alpha=0.6); lim = [-4.5, 5.5]; ax[0].plot(lim, lim, "k-", lw=0.6)
    for t in (-2, 2):
        ax[0].axvline(t, color="orange", ls="--", lw=0.7); ax[0].axhline(t, color="orange", ls="--", lw=0.7)
    ax[0].set_xlabel("EPR 1990–2025 (m/yr)"); ax[0].set_ylabel("LRR, all years (m/yr)"); ax[0].set_title(f"EPR vs LRR (r = {ma['corr']:.2f}, n = {ma['n']})")
    mean = (v.EPR_m_yr + v.lrr) / 2; diff = v.lrr - v.EPR_m_yr
    ax[1].scatter(mean, diff, s=8, alpha=0.6); ax[1].axhline(diff.mean(), color="r"); ax[1].axhline(diff.mean() + 1.96 * diff.std(), color="r", ls="--"); ax[1].axhline(diff.mean() - 1.96 * diff.std(), color="r", ls="--")
    ax[1].set_xlabel("mean of EPR and LRR"); ax[1].set_ylabel("LRR − EPR (m/yr)"); ax[1].set_title(f"Bland–Altman: mean difference {diff.mean():+.2f} m/yr, ±1.96 SD = {1.96*diff.std():.2f}")
    fig.tight_layout(); fig.savefig(out / "Fig_6_epr_vs_lrr.png", dpi=200); plt.close(fig)

    sa = res.get("sa")
    if sa:
        both = sa["both"]
        fig, ax = plt.subplots(1, 2, figsize=(12, 5))
        ax[0].scatter(both.EPR_m_yr_v, both.EPR_m_yr_r, s=8, alpha=0.6); ax[0].plot([-4.5, 5.5], [-4.5, 5.5], "k-", lw=0.6)
        ax[0].set_xlabel("EPR, vector_clean (m/yr)"); ax[0].set_ylabel("EPR, raster_clean (m/yr)"); ax[0].set_title(f"Two independent shoreline sets, same transects (r = {sa['epr_corr']:.2f}, n = {sa['n_pairs']})")
        p = sa["positions"]
        ax[1].bar(p.year.astype(str), p.robust_sd_m, color="#1f77b4", label="robust SD of the difference"); ax[1].plot(p.year.astype(str), p.p95_abs_m, "ro-", label="95th percentile |difference|")
        ax[1].set_ylabel("metres"); ax[1].set_title("Position disagreement raster − vector, per year"); ax[1].legend()
        fig.tight_layout(); fig.savefig(out / "Fig_6_source_agreement.png", dpi=200); plt.close(fig)


def render(res: dict, cfg: dict) -> Path:
    runs, rob, ma, vp = res["runs"], res["rob"], res["ma"], res["vp"]
    sa = res.get("sa")
    base = runs[runs.scenario == "base"].iloc[0]
    thr_lo = runs[runs.scenario == "thr_-0.5"].iloc[0]; thr_hi = runs[runs.scenario == "thr_+0.5"].iloc[0]
    lrr = runs[runs.scenario == "classify_by_LRR"].iloc[0]; est = runs[runs.scenario == "with_estuarine"].iloc[0]
    robust = rob[rob.robust].barangay.tolist(); notrobust = rob[~rob.robust].barangay.tolist()
    insens = runs[runs.scenario.isin(["spacing_25", "spacing_100", "smooth_100", "smooth_400", "multihit_farthest", "offset_landward_300"])]
    max_shift = float(max(abs(insens.pct_Medium - base.pct_Medium).max(), abs(insens.pct_Low - base.pct_Low).max()))
    conf = ma["confusion"]
    order = {"Low": 0, "Medium": 1, "High": 2}
    n_dis = int(conf.values.sum() - sum(conf.loc[i, i] for i in conf.index if i in conf.columns))
    epr_hi = int(sum(conf.loc[i, j] for i in conf.index for j in conf.columns if order[i] > order[j]))
    n_high_sm = int(round(runs[runs.scenario == "smooth_400"].pct_High.iloc[0] * runs[runs.scenario == "smooth_400"].n_valid.iloc[0] / 100))
    max_ero = float(ma["v"].EPR_m_yr.min())
    dis_brg = ""
    if sa:
        bt = sa["both"]
        from .risk import classify as _cl
        cv = _cl(bt.EPR_m_yr_v.values, cfg["risk"]["low_max"], cfg["risk"]["medium_max"], cfg["risk"]["accretion_class"]); cr = _cl(bt.EPR_m_yr_r.values, cfg["risk"]["low_max"], cfg["risk"]["medium_max"], cfg["risk"]["accretion_class"])
        dis_brg = ", ".join(f"{k} ({v})" for k, v in bt[cv != cr].barangay_v.value_counts().items())
        band = bt[cv != cr].EPR_m_yr_v
    txt = f"""# 05 — Sensitivity, validation and robustness (Phase 6)

*Generated by `make sensitivity`. All runs use the same engine and the primary shoreline set (`{cfg['shoreline_set']}`); one choice is changed at a time. "% of the coast" = share of valid 50 m transects (equal spacing, so it is proportional to kilometres).*

## Executive summary — which conclusions are robust?

1. **Technical choices do not matter.** Transect spacing (25/100 m), baseline smoothing (100/400 m), baseline offset (150→300 m) and the multi-hit rule change the share of any class by at most **{max_shift:.1f} percentage points**.
2. **The thresholds matter a lot** because most of the coast sits near the 2 m/yr boundary: moving both cut-offs by −0.5 m/yr makes {thr_lo.pct_Medium:.0f} % of the coast Medium; by +0.5 m/yr only {thr_hi.pct_Medium:.0f} % (base {base.pct_Medium:.0f} %). The class map is therefore a statement about a **convention**, not a natural boundary.
3. **EPR vs LRR:** r = {ma['corr']:.2f}; they disagree on the class for {ma['disagree_pct']:.0f} % of transects ({epr_hi} of the {n_dis} disagreements are "EPR higher class than LRR"). Classifying with LRR gives {lrr.pct_Medium:.0f} % Medium instead of {base.pct_Medium:.0f} %.
4. **Robust (same class in ≥ 90 % of the runs):** {', '.join(robust) or 'none'}. **Not robust:** {', '.join(notrobust) or 'none'}.
5. **No High class on the open coast in any run except two**: with estuarine banks included ({est.pct_High:.1f} % High, all at the river mouth) and with the 400 m smoothing ({runs[runs.scenario=='smooth_400'].pct_High.iloc[0]:.1f} % = {n_high_sm} transect(s)). The thesis statement "High risk (> 5 m/yr) along Bulala Sur/Bulala Norte" is **not** reproduced under any tested choice; the highest open-coast erosion rate among valid transects is {max_ero:.1f} m/yr ({'Medium' if abs(max_ero) <= 5 else 'High'}).
6. **Independent source:** {('the raster-derived set (Earth Engine masks, cleaned) gives the same class for ' + f"{sa['class_agree_pct']:.0f} % of {sa['n_pairs']} transects, EPR r = {sa['epr_corr']:.2f}, difference RMSE {sa['epr_diff_rmse']:.2f} m/yr") if sa else 'not available'}.

## 1. One-at-a-time sensitivity runs

{md(runs[['scenario','description','transects','n_valid','pct_Low','pct_Medium','pct_High','mean_EPR','median_EPR']], floatfmt='{:,.2f}')}

![classes](../outputs/maps/Fig_6_sensitivity_class_shares.png)

Per-barangay stability (dominant class = class with most transects; worst = highest class holding ≥ 10 % of transects):

{md(rob, floatfmt='{:,.0f}')}

Full per-run per-barangay table: `outputs/tables/sensitivity_barangay_class.csv`.

## 2. EPR and LRR

EPR uses only the first and last date; LRR uses all five. With five dates the LRR is the more robust estimator (it is not hostage to two noisy end points) but the thesis defines the risk from EPR, so EPR remains the primary class and LRR is shown beside it.

![epr lrr](../outputs/maps/Fig_6_epr_vs_lrr.png)

Mean LRR − EPR = {ma['mean_diff']:+.2f} m/yr (SD {ma['sd_diff']:.2f}). Class confusion (rows EPR, columns LRR):

{md(ma['confusion'], index=True)}

## 3. Agreement between independent shoreline sets
"""
    if sa:
        txt += f"""
Both sets are measured on the **same** transects (the baseline is built once from the vector set, decision D-09). The raster-derived set comes from the Earth Engine edge-pixel masks; the vector set is the hand-digitised/unknown-origin lines. They are independent processing chains, though they may share the same underlying imagery, so common errors are *not* captured.

{md(sa['positions'], floatfmt='{:,.1f}')}

* Median bias per year is within ±{sa['positions'].bias_median_m.abs().max():.0f} m; the robust SD of the position difference is {sa['positions'].robust_sd_m.min():.0f}–{sa['positions'].robust_sd_m.max():.0f} m; {sa['positions'].share_within_60m.min()*100:.0f}–{sa['positions'].share_within_60m.max()*100:.0f} % of transects agree within 2 pixels (60 m).
* Rates: EPR r = {sa['epr_corr']:.2f}, mean difference {sa['epr_diff_mean']:+.2f} m/yr, RMSE {sa['epr_diff_rmse']:.2f} m/yr, 95 % of differences below {sa['epr_diff_p95']:.2f} m/yr; LRR difference RMSE {sa['lrr_diff_rmse']:.2f} m/yr.
* Class agreement {sa['class_agree_pct']:.1f} % (rows vector, columns raster):

{md(sa['confusion'], index=True)}

![sources](../outputs/maps/Fig_6_source_agreement.png)

### Proposed uncertainty values (PROPOSALS — for the students to confirm, NOT used in any result)

The last column of the table above, `proposal_sigma_per_date_m`, is the robust SD of the between-set difference divided by √2 (if the two sets had equal, independent errors, each would carry that share). Plain reading: **a defensible per-date shoreline position error for this coast is of the order of 7–12 m from the evidence of the two sets, but the Landsat pixel (30 m) is the stated resolution of the source imagery and the physical floor for any Landsat-based shoreline.** Until the students supply georeferencing, digitising and tidal components, `config.uncertainty_m` stays `null`; if they accept the evidence, a reasonable choice would be pixel = 30 (stated), digitizing ≈ 10, georeferencing and tidal to be estimated from the imagery metadata and a tide table. With the full 30 m the EPR uncertainty is ±1.21 m/yr, which is larger than the Low/Medium boundary distance for most of the coast (see `class_may_flip` in Table 4.2 extended).

A conclusion that **does** depend on the source: {int(sa['confusion'].values.sum() - np.trace(sa['confusion'].values))} of {sa['n_pairs']} transects change class between the sets; their vector-set EPR lies between {band.min():.2f} and {band.max():.2f} m/yr (i.e. near the 2 m/yr boundary), by barangay: {dis_brg}.
"""
    else:
        txt += "\nNo second shoreline set was available.\n"
    txt += f"""
## 4. Field validation template (nothing here claims validation was done)

`outputs/field_validation/field_validation_points.csv` (and `.gpkg`) lists **{len(vp)} verification points** chosen deterministically: at least one per barangay × class stratum present, spread evenly along each stratum, each at the 2025 shoreline position of a valid transect. Blank columns are for the students to fill in the field: date, recorder, GPS device and accuracy, distance to the vegetation line and to the waterline, tide state/time, presence and condition of protection structures, evidence of erosion (scarp, undercut trees, exposed roots), photo file names, notes. A printable checklist is in `docs/field_validation_form.md`.

{md(vp[['point_id','barangay','predicted_class','transect_id','EPR_m_yr','LRR_m_yr','confidence','lon','lat']], floatfmt='{:,.4f}')}

*Why these checks:* a satellite shoreline can be right in position and still be a poor "erosion indicator" (a waterline moves with the tide; a vegetation line or erosion scarp does not). One visit with a GPS and a tape across 20 points tells the panel more than any further processing.
"""
    out = REPO_ROOT / "docs" / "05_sensitivity_validation.md"
    out.write_text(txt, encoding="utf-8")
    return out
